import type { Metadata } from 'next';
import '@/app/globals.css';

import MainHeader from '@/components/mainheader';

import { Crimson_Pro, Inter, Poppins } from 'next/font/google';

const crimsonPro = Crimson_Pro({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-crimson-pro'
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
  weight: '500'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimsonPro.variable} ${inter.variable} ${poppins.variable}`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
